### ISSUE TITLE
JST-PH-2-SMT-RA positive and negative labels reversed?

### ISSUE THREAD

**Issue by jessehamner** [adafruit/Adafruit-Eagle-Library#16]
It appears that the "positive" and "negative" labels on the surface-mount right-angle 2-pin JST (male) jack are reversed, compared to the other three 2-pin JST jacks. I request the labels be changed.
![screen shot 2015-04-27 at 8 53 20 am](https://cloud.githubusercontent.com/assets/1970982/7348902/fe0ee05c-ecba-11e4-8a0a-0a2cc5540f3f.png)
![screen shot 2015-04-27 at 8 53 11 am](https://cloud.githubusercontent.com/assets/1970982/7348903/fe10b10c-ecba-11e4-996f-a62ffac961a3.png)

**Comment by syncon303** [comment]
No changes are necessary. If you refer to the connector datasheet (http://www.jst-mfg.com/product/pdf/eng/ePH.pdf , page1 at the bottom) you'll notice that pin 1 is on opposite side for the two versions of the connector.

**Comment by jessehamner** [comment]
Though it's a bit confusing for JST to switch polarity like that, I accept that explanation. Thanks very much for replying.
